; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

# N16R8 QIO Flash + OPI PSRAM 核心配置
board_build.flash_mode = qio
board_build.arduino.memory_type = qio_opi
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.partitions = default_16MB.csv

# 全套PSRAM底层宏，缺一不可
board_build.extra_flags =
  -DBOARD_HAS_PSRAM
  -DCONFIG_SPIRAM
  -DCONFIG_SPIRAM_SUPPORT=1
  -DCONFIG_SPIRAM_MODE_OPI=1

upload_speed = 921600
monitor_speed = 115200

#挂载文件系统为littlefs
board_build.filesystem = littlefs

#加载oled屏幕驱动库
lib_deps =
    olikraus/U8g2    #oled驱动库依赖
    bblanchon/ArduinoJson    #json解析库依赖

lib_ldf_mode = deep+